// Additive maintenance import. Never invoke the old wipe/full-seed script.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const assert=require('node:assert/strict');
const {connect,accounts}=require('./db');
const filename=path.join(__dirname,'plan.json'),receiptFile=path.join(__dirname,'receipt.json');
const snake=s=>s.replace(/[A-Z]/g,m=>'_'+m.toLowerCase());
const rows=a=>JSON.stringify(a.map(x=>Object.fromEntries(Object.entries(x).map(([k,v])=>[snake(k),v]))));
const ids=xs=>xs.map(x=>x.id);
async function counts(c,tables){const out={};for(const t of tables)out[t]=Number((await c.query('SELECT count(*) AS n FROM '+t)).rows[0].n);return out;}
function validate(plan){assert.equal(plan.listings.length,500);assert.equal(plan.landmarks.length,100);assert.equal(plan.complexes.length,30);assert.equal(plan.reviews.length,1500);assert.equal(plan.inventory.length,500);assert.equal(plan.inventoryDays,91);assert.match(plan.inventoryStart,/^\d{4}-\d{2}-\d{2}$/);const ownCloud=JSON.parse(fs.readFileSync(path.join(__dirname,'../cloudinary-images.json'))).cloudName;const url=u=>{const p=new URL(u);assert.equal(p.protocol,'https:');assert.equal(p.hostname,'res.cloudinary.com');assert.ok(p.pathname.startsWith('/'+ownCloud+'/image/upload/'));};const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../cloudinary-images.json')));const verified=new Set(Object.values(manifest.assets).filter(x=>x.state==='verified').map(x=>x.secureUrl));
 const all=[...plan.landmarks,...plan.complexes,...plan.listings,...plan.reviews,...plan.inventory];assert.equal(new Set(all.map(x=>x.id)).size,all.length);
 const complexes=new Map(plan.complexes.map(x=>[x.id,x]));for(const x of [...plan.landmarks,...plan.complexes,...plan.listings]){assert.ok(x.description.length>300);assert.ok(Number.isFinite(x.latitude)&&x.latitude>=8&&x.latitude<=24);assert.ok(Number.isFinite(x.longitude)&&x.longitude>=102&&x.longitude<=111);url(x.thumbnailUrl);assert.ok(verified.has(x.thumbnailUrl));for(const image of x.galleryUrls||x.attributes?.galleryUrls||[]){url(image);assert.ok(verified.has(image));}}
 for(const l of plan.listings){assert.ok(!l.title.startsWith('[Mẫu]'));assert.equal(plan.recordOrigins?.listings,'synthetic');assert.ok(l.title.length<=255);assert.ok(!l.description.includes('DỮ LIỆU MẪU'));assert.ok(l.basePrice>0);assert.equal(l.status,'ACTIVE');assert.equal(l.attributes.categoryType,l.category==='SVC'?'SVC_'+l.subCategory:l.category);assert.ok(l.attributes.galleryUrls.length>=5);if(l.complexId){assert.equal(l.hostId,complexes.get(l.complexId).hostId);assert.equal(l.province,complexes.get(l.complexId).province);}const rr=plan.reviews.filter(r=>r.listingId===l.id);assert.equal(rr.length,3);assert.equal(new Set(rr.map(r=>r.userId)).size,3);assert.equal(l.totalReviews,3);assert.equal(l.averageRating,Math.round(rr.reduce((sum,r)=>sum+r.rating,0)/3*10)/10);}
 for(const r of plan.reviews){assert.ok(r.comment.startsWith('[Đánh giá giả lập'));assert.ok(r.comment.includes('Không phải đánh giá của khách hàng thật'));assert.ok(Number.isInteger(r.rating)&&r.rating>=1&&r.rating<=5);}
 for(const i of plan.inventory){assert.ok(plan.listings.some(l=>l.id===i.listingId));assert.ok(i.scheduleConfig.defaultQuantity>0);if(i.category!=='STAY'){assert.equal(i.scheduleConfig.timeSlots.length,3);assert.equal(new Set(i.scheduleConfig.timeSlots.map(s=>s.slot)).size,3);}}
 return{landmarks:100,complexes:30,listings:500,reviews:1500,inventoryConfigs:500,inventoryCalendars:96460};}
async function apply(){const plan=JSON.parse(fs.readFileSync(filename)),expected=validate(plan);if(!process.argv.includes('--apply')){console.log(JSON.stringify({mode:'validate only',...expected}));return;}
 const users=new Map((await accounts()).map(x=>[x.id,x]));for(const x of plan.listings)assert.ok(users.get(x.hostId)?.roles.some(r=>r==='HOST'||r==='ENTERPRISE'),'Owner must be an existing active seed HOST/ENTERPRISE');for(const x of plan.complexes)assert.ok(users.get(x.hostId)?.roles.includes('ENTERPRISE'),'Complex owner must be an existing active seed ENTERPRISE');for(const r of plan.reviews)assert.ok(users.get(r.userId)?.roles.includes('USER'),'Reviewer must be an existing active seed USER');
 const catalog=await connect('CatalogandListing'),booking=await connect('BookingandInventory');let bookingCommitted=false,catalogCommitted=false,bookingInserted=false;const batchIds=ids(plan.listings);const journalDir=path.join(__dirname,'../.image-migration/expansion');fs.mkdirSync(journalDir,{recursive:true,mode:0o700});const sha=crypto.createHash('sha256').update(fs.readFileSync(filename)).digest('hex');let receipt;
 try{await catalog.query('BEGIN');await catalog.query("SET LOCAL lock_timeout='10s'");await catalog.query("SET LOCAL statement_timeout='120s'");await catalog.query('SELECT pg_advisory_xact_lock(hashtext($1))',[plan.batchId]);await booking.query('BEGIN');await booking.query("SET LOCAL lock_timeout='10s'");await booking.query("SET LOCAL statement_timeout='120s'");await booking.query('SELECT pg_advisory_xact_lock(hashtext($1))',[plan.batchId]);
  const existing=Number((await catalog.query('SELECT count(*) AS n FROM listings WHERE id=ANY($1::uuid[])',[batchIds])).rows[0].n);if(existing===500){await booking.query('ROLLBACK');await catalog.query('ROLLBACK');console.log('Batch already exists; no updates to listings, reviews or live inventory. Run verify-plan.js.');return;}assert.equal(existing,0,'Partial Catalog batch: inspect the journal before resuming');for(const [table,list]of[['landmarks',plan.landmarks],['complexes',plan.complexes],['reviews',plan.reviews]])assert.equal(Number((await catalog.query('SELECT count(*) AS n FROM '+table+' WHERE id=ANY($1::uuid[])',[ids(list)])).rows[0].n),0,'Unexpected identifier collision: '+table);
  const invExisting=Number((await booking.query('SELECT count(*) AS n FROM inventory_configs WHERE listing_id=ANY($1::uuid[])',[batchIds])).rows[0].n);assert.equal(invExisting,0,'An orphan inventory batch exists: inspect and reconcile before resuming');
  receipt={batchId:plan.batchId,planSha256:sha,startedAt:new Date().toISOString(),inventoryStart:plan.inventoryStart,expected,before:{catalog:await counts(catalog,['landmarks','complexes','listings','reviews']),booking:await counts(booking,['inventory_configs','inventory_calendars','inventory_locks'])},status:'prepared'};
  fs.writeFileSync(path.join(journalDir,'journal.json'),JSON.stringify(receipt,null,2)+'\n',{mode:0o600});fs.copyFileSync(filename,path.join(journalDir,'applied-plan.json'));
  // Existing province/name pairs are protected even if IDs differ.
  const real=await catalog.query('SELECT name,latitude,longitude FROM landmarks');const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/gi,'d').toLowerCase().replace(/[^a-z0-9]/g,'');for(const p of plan.landmarks)assert.ok(!real.rows.some(x=>normalize(x.name)===normalize(p.name)),'Existing landmark name: '+p.name);
  await catalog.query(`INSERT INTO landmarks(id,name,description,province,latitude,longitude,location,radius_meters,thumbnail_url,gallery_urls,is_featured,status,created_at,updated_at) SELECT id,name,description,province,latitude,longitude,ST_SetSRID(ST_MakePoint(longitude,latitude),4326),radius_meters,thumbnail_url,gallery_urls,is_featured,status,NOW(),NOW() FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,name text,description text,province text,latitude double precision,longitude double precision,radius_meters integer,thumbnail_url text,gallery_urls jsonb,is_featured boolean,status text)`,[rows(plan.landmarks)]);
  await catalog.query(`INSERT INTO complexes(id,host_id,name,description,province,latitude,longitude,location,thumbnail_url,gallery_urls,status,created_at,updated_at) SELECT id,host_id,name,description,province,latitude,longitude,ST_SetSRID(ST_MakePoint(longitude,latitude),4326),thumbnail_url,gallery_urls,status,NOW(),NOW() FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,host_id uuid,name text,description text,province text,latitude double precision,longitude double precision,thumbnail_url text,gallery_urls jsonb,status text)`,[rows(plan.complexes)]);
  await catalog.query(`INSERT INTO listings(id,host_id,complex_id,title,description,category,sub_category,province,base_price,price_unit,latitude,longitude,location,thumbnail_url,attributes,average_rating,total_reviews,status,created_at,updated_at) SELECT id,host_id,complex_id,title,description,category,sub_category,province,base_price,price_unit,latitude,longitude,ST_SetSRID(ST_MakePoint(longitude,latitude),4326),thumbnail_url,attributes,average_rating,total_reviews,status,NOW(),NOW() FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,host_id uuid,complex_id uuid,title text,description text,category text,sub_category text,province text,base_price numeric,price_unit text,latitude double precision,longitude double precision,thumbnail_url text,attributes jsonb,average_rating numeric,total_reviews integer,status text)`,[rows(plan.listings)]);
  await catalog.query(`INSERT INTO reviews(id,listing_id,user_id,rating,comment,images,created_at) SELECT id,listing_id,user_id,rating,comment,images,NOW() FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,listing_id uuid,user_id uuid,rating integer,comment text,images jsonb)`,[rows(plan.reviews)]);
  await booking.query(`INSERT INTO inventory_configs(id,listing_id,category,schedule_config,is_active,created_at,updated_at) SELECT id,listing_id,category,schedule_config,is_active,NOW(),NOW() FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,listing_id uuid,category text,schedule_config jsonb,is_active boolean)`,[rows(plan.inventory)]);bookingInserted=true;
  await booking.query(`INSERT INTO inventory_calendars(id,listing_id,date,time_slot,available_quantity,status,version,created_at,updated_at) SELECT gen_random_uuid(),c.listing_id,$2::date+days.n,s.slot,s.quantity,'AVAILABLE',0,NOW(),NOW() FROM inventory_configs c CROSS JOIN generate_series(0,90) AS days(n) CROSS JOIN LATERAL jsonb_to_recordset(CASE WHEN c.category='STAY' THEN jsonb_build_array(jsonb_build_object('slot','ALL_DAY','quantity',c.schedule_config->'defaultQuantity')) ELSE c.schedule_config->'timeSlots' END) AS s(slot text,quantity integer) WHERE c.listing_id=ANY($1::uuid[])`,[batchIds,plan.inventoryStart]);
  assert.equal(Number((await booking.query('SELECT count(*) AS n FROM inventory_calendars WHERE listing_id=ANY($1::uuid[])',[batchIds])).rows[0].n),expected.inventoryCalendars);
  assert.equal(Number((await catalog.query("SELECT count(*) AS n FROM listings WHERE id=ANY($1::uuid[]) AND status='ACTIVE' AND title_normalized IS NOT NULL AND location IS NOT NULL",[batchIds])).rows[0].n),500);
  const geo=await catalog.query('SELECT count(*) AS n FROM landmarks WHERE id=ANY($1::uuid[]) AND name_normalized IS NOT NULL AND ST_SRID(location)=4326',[ids(plan.landmarks)]);assert.equal(Number(geo.rows[0].n),100);
  // Publish Catalog only after usable inventory commits. No external paid orders are created.
  await booking.query('COMMIT');bookingCommitted=true;receipt.status='inventory_committed';fs.writeFileSync(path.join(journalDir,'journal.json'),JSON.stringify(receipt,null,2)+'\n');await catalog.query('COMMIT');catalogCommitted=true;
  receipt.status='committed';receipt.completedAt=new Date().toISOString();receipt.after={catalog:await counts(catalog,['landmarks','complexes','listings','reviews']),booking:await counts(booking,['inventory_configs','inventory_calendars','inventory_locks'])};
  fs.writeFileSync(receiptFile,JSON.stringify(receipt,null,2)+'\n');fs.writeFileSync(path.join(journalDir,'journal.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
 }catch(e){if(!catalogCommitted)await catalog.query('ROLLBACK').catch(()=>{});if(!bookingCommitted)await booking.query('ROLLBACK').catch(()=>{});
  if(bookingCommitted&&bookingInserted&&!catalogCommitted){const published=Number((await catalog.query('SELECT count(*) AS n FROM listings WHERE id=ANY($1::uuid[])',[batchIds])).rows[0].n);if(published===0){await booking.query('BEGIN');await booking.query('SELECT pg_advisory_xact_lock(hashtext($1))',[plan.batchId]);const locked=Number((await booking.query('SELECT count(*) AS n FROM inventory_locks l JOIN inventory_calendars c ON c.id=l.inventory_calendar_id WHERE c.listing_id=ANY($1::uuid[])',[batchIds])).rows[0].n);if(locked===0){await booking.query('DELETE FROM inventory_calendars WHERE listing_id=ANY($1::uuid[])',[batchIds]);await booking.query('DELETE FROM inventory_configs WHERE listing_id=ANY($1::uuid[])',[batchIds]);await booking.query('COMMIT');if(receipt)receipt.status='compensated';}else await booking.query('ROLLBACK');}else if(receipt)receipt.status='commit_outcome_requires_verification';if(receipt)fs.writeFileSync(path.join(journalDir,'journal.json'),JSON.stringify(receipt,null,2)+'\n');}
  throw e;
 }finally{await booking.end();await catalog.end();}
}
if(require.main===module)apply().catch(e=>{console.error(e.message);process.exitCode=1;});module.exports={validate,counts};
