const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {accounts}=require('./db');const {LISTING_IMAGE_POOLS,IMAGE_POOLS}=require('../vietnam-data');
const highlights=require('./place-highlights.json');
const batch='gotravel-expansion-2026-10-04-v1';
const id=key=>{const h=crypto.createHash('sha1').update(batch+':'+key).digest('hex').slice(0,32).split('');h[12]='5';h[16]='8';const s=h.join('');return[s.slice(0,8),s.slice(8,12),s.slice(12,16),s.slice(16,20),s.slice(20)].join('-');};
const fold=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/gi,'d').toLowerCase().trim();
const choose=(a,i)=>a[((i%a.length)+a.length)%a.length];
const gallery=(a,i)=>Array.from({length:Math.min(5,a.length)},(_,n)=>choose(a,i+n));
const slots=[{slot:'08:00 - 10:00',quantity:8},{slot:'13:00 - 15:00',quantity:8},{slot:'16:00 - 18:00',quantity:8}];
const expSlots=[{slot:'08:00 - 11:00',quantity:8},{slot:'12:00 - 15:00',quantity:8},{slot:'15:30 - 18:30',quantity:8}];
const note='DỮ LIỆU MẪU phục vụ phát triển và kiểm thử GoTravel. Tên cơ sở, vị trí dịch vụ, giá, tiện nghi, lịch còn chỗ và đánh giá dưới đây là giả lập; không phải quảng cáo hay xác nhận nhận đặt chỗ của doanh nghiệp có thật. Ảnh dịch vụ là ảnh minh họa.';
const kindText={BEACH:['bãi biển và cảnh quan ven bờ','dạo bộ ven biển, quan sát cảnh quan và chụp ảnh'],SPIRITUAL:['di tích tín ngưỡng và kiến trúc','tham quan kiến trúc và tìm hiểu không gian văn hóa'],MUSEUM:['bảo tàng và không gian trưng bày','tìm hiểu các chủ đề trưng bày và lịch sử địa phương'],CAVE:['hang động và cảnh quan tự nhiên','tham quan theo tuyến được đơn vị quản lý cho phép'],NATIONAL_PARK:['vườn quốc gia hoặc khu bảo tồn thiên nhiên','quan sát thiên nhiên trên những tuyến được phép'],NATURE:['cảnh quan tự nhiên','tham quan cảnh quan, đi bộ nhẹ và chụp ảnh'],PARK:['công viên và không gian công cộng','đi dạo và khám phá cảnh quan đô thị'],HERITAGE:['di tích hoặc điểm tham quan văn hóa','khám phá kiến trúc và văn hóa địa phương']};
function credit(p){return `Ảnh "${p.image.fileTitle.replace(/^File:/,'')}" (${p.title}): ${p.image.author||'Tác giả theo trang nguồn'}, ${p.image.license}; ${p.image.sourcePage}. Ảnh đã đổi kích thước và chuyển WebP; giữ giấy phép nguồn. ${p.image.licenseUrl||''}`;}
function landmarkDescription(p){const [type,activity]=kindText[p.kind];return `${highlights[p.title]}\n\n${p.title} là điểm tham quan thuộc nhóm ${type}, được ghi nhận tại ${p.province}. Thông tin tên gọi, tọa độ và ảnh đại diện được đối chiếu từ trang nguồn: ${p.wikipediaUrl}. Có thể lên lịch ${activity} và kết hợp các điểm lân cận; thời lượng thực tế phụ thuộc thời tiết, tuyến tham quan và quy định của đơn vị quản lý. Hãy kiểm tra giờ mở cửa, giá vé và điều kiện tiếp cận trước chuyến đi; dữ liệu seed không xác nhận thông tin vận hành theo thời gian thực. Không xả rác, không tác động tới di tích và tuân thủ biển hướng dẫn tại chỗ. Google Maps: ${p.googleMapsUrl}\n\n${credit(p)}`;}
const stayTypes=['Khách sạn boutique','Căn hộ có bếp','Villa gia đình','Homestay sân vườn','Bungalow','Resort nghỉ dưỡng','Cabin gỗ','Hostel phòng riêng','Farmstay','Lều glamping','Nhà nghỉ ven phố'];
const propertyTypes=['hotel','apartment','villa','homestay','bungalow','resort','cabin','hostel','farmstay','camping','guesthouse'];
const stayAmenities=['Wifi tốc độ cao','Điều hòa nhiệt độ','Khăn tắm sạch','Máy sấy tóc','Chỗ đỗ xe miễn phí','Bếp nấu đầy đủ dụng cụ','Máy giặt & sấy','Ban công thoáng mát','Đồ vệ sinh cá nhân miễn phí','Hồ bơi ngoài trời','Máy pha cà phê'];
const svc={
 PHOTOGRAPHY:{name:'Chụp ảnh du lịch',details:i=>({providerType:'Nhiếp ảnh gia mẫu',durationMinutes:60+(i%3)*30,deliveryDays:3,deliverables:'30 ảnh chỉnh màu và 5 ảnh chỉnh sửa chi tiết; giao qua thư viện trực tuyến',cameraGear:'Máy ảnh mirrorless, ống kính chân dung và đèn trợ sáng'}),desc:'Buổi chụp hình chân dung, cặp đôi hoặc gia đình được thiết kế theo lịch trình du lịch. Kịch bản gồm trao đổi ý tưởng, hướng dẫn tạo dáng và chọn khung cảnh công cộng được phép chụp. Chi phí di chuyển ngoài bán kính phục vụ và vé vào điểm tham quan chưa bao gồm.'},
 CHEF:{name:'Đầu bếp tại chỗ',details:i=>({cuisineType:['Việt Nam',choose(['Món miền Bắc','Món miền Trung','Món miền Nam'],i)],includesIngredients:true,cleanUpAfter:true,specialDietary:['Thực đơn chay theo yêu cầu','Trao đổi dị ứng trước buổi nấu']}),desc:'Thực đơn mẫu gồm món khai vị, món chính và tráng miệng cho nhóm nhỏ. Đầu bếp chuẩn bị nguyên liệu, nấu tại căn hộ có bếp và dọn khu vực chế biến sau buổi ăn. Khách cần trao đổi khẩu vị, dị ứng và điều kiện bếp trước khi chọn lịch.'},
 MASSAGE:{name:'Massage thư giãn',details:i=>({massageType:['Thư giãn nhẹ','Massage vai gáy'],durationMinutes:60,genderPreference:'Không yêu cầu',equipmentProvided:'Giường massage gấp, khăn sạch và dầu nền'}),desc:'Gói mẫu tập trung vào thư giãn vai gáy và giảm cảm giác mỏi sau di chuyển. Quy trình gồm trao đổi nhu cầu, kiểm tra sự thoải mái của khách và thực hiện với lực phù hợp. Dịch vụ không chẩn đoán hoặc điều trị bệnh; khách có tình trạng sức khỏe đặc biệt cần hỏi chuyên gia y tế trước.'},
 PREPARED_MEALS:{name:'Suất ăn chuẩn bị sẵn',details:i=>({mealType:['Bữa trưa','Bữa tối'],deliveryFrequency:'Theo lịch đặt trong ngày',mealsPerDay:2,caloriesPerDay:'Khoảng 1.600–2.000 kcal theo thực đơn mẫu',heatingInstructions:'Giữ lạnh theo hướng dẫn của đơn vị cung cấp, làm nóng kỹ trước khi dùng; không dùng nếu bao bì có dấu hiệu bất thường'}),desc:'Bộ suất ăn mẫu dành cho khách lưu trú dài ngày với lựa chọn món Việt và rau theo mùa. Mỗi phần được đóng hộp, ghi thành phần và hướng dẫn bảo quản. Giá tính theo phần; phí giao ngoài bán kính phục vụ và yêu cầu chế độ ăn riêng được xác nhận trước.'},
 TRAINING:{name:'Lớp kỹ năng du lịch',details:i=>({skillTaught:choose(['Chụp ảnh bằng điện thoại','Yoga cơ bản','Vẽ ký họa cảnh quan','Pha cà phê thủ công'],i),level:'Cơ bản',durationMinutes:90,groupSize:{min:1,max:8},equipmentProvided:'Bộ dụng cụ thực hành cơ bản theo chủ đề'}),desc:'Lớp mẫu theo nhóm nhỏ, có giới thiệu kỹ năng, phần hướng dẫn và thời gian thực hành. Người mới bắt đầu có thể tham gia; khách trao đổi nhu cầu hoặc giới hạn vận động trước buổi học. Dụng cụ chuyên môn theo chủ đề được liệt kê trong cấu hình dịch vụ.'},
 MAKEUP:{name:'Trang điểm du lịch',details:i=>({makeupStyle:['Tự nhiên','Chụp ảnh ngoài trời'],includesHair:true,durationMinutes:60,brandsUsed:['Bộ sản phẩm minh họa; nhãn hiệu xác nhận khi tư vấn']}),desc:'Gói trang điểm mẫu dành cho buổi chụp ảnh hoặc sự kiện nhỏ trong chuyến đi. Quy trình gồm trao đổi phong cách, làm sạch dụng cụ và hoàn thiện nền, mắt, môi cùng tạo kiểu tóc đơn giản. Khách nên báo tiền sử dị ứng mỹ phẩm và yêu cầu thử sản phẩm trước khi sử dụng.'},
 HAIR_STYLING:{name:'Tạo kiểu tóc',details:i=>({serviceType:['Tạo kiểu nhẹ','Sấy và uốn tạm thời'],targetGender:'Mọi giới tính',chemicalsIncluded:false,durationMinutes:45}),desc:'Gói mẫu tạo kiểu tóc nhanh cho ảnh du lịch hoặc buổi gặp mặt. Có bước tư vấn độ dài, kiểu tóc và làm sạch dụng cụ giữa các lượt. Dịch vụ không bao gồm nhuộm, tẩy hoặc xử lý hóa chất; khách cần báo tình trạng da đầu và giới hạn sử dụng nhiệt.'},
 SPA:{name:'Chăm sóc spa',details:i=>({treatments:['Chăm sóc da cơ bản','Thư giãn tay chân'],organicProductsOnly:false,durationMinutes:90,genderPreference:'Không yêu cầu'}),desc:'Liệu trình spa mẫu gồm trao đổi nhu cầu, vệ sinh dụng cụ và chăm sóc nhẹ trong không gian riêng. Thành phần sản phẩm và mức độ phù hợp được xác nhận trước khi thực hiện. Không bao gồm thủ thuật xâm lấn hoặc cam kết điều trị; khách có dị ứng cần báo trước.'},
 CATERING:{name:'Tiệc nhóm và catering',details:i=>({eventType:['Gặp mặt nhóm du lịch','Sinh nhật nhỏ'],menuType:choose(['Set menu Việt','Buffet nhỏ','Thực đơn chay'],i),guestCapacity:{min:6,max:30},includesStaff:true,includesTableware:true}),desc:'Gói catering mẫu dành cho nhóm du lịch gồm thực đơn, bố trí bàn ăn, nhân sự phục vụ và thu dọn. Khách thống nhất số người, dị ứng thực phẩm, thời gian và điều kiện địa điểm trước khi đặt. Phí thuê địa điểm, đồ uống bổ sung và trang trí theo yêu cầu chưa bao gồm.'}
};
function coordinates(p,i){const angle=i*2.399963;const km=.35+(i%7)*.2;return{latitude:Number((p.latitude+Math.cos(angle)*km/111).toFixed(6)),longitude:Number((p.longitude+Math.sin(angle)*km/(111*Math.cos(p.latitude*Math.PI/180))).toFixed(6))};}
function stay(p,i){const guests=2+(i%4)*2,bedrooms=Math.ceil(guests/3),type=choose(stayTypes,i),images=gallery(LISTING_IMAGE_POOLS.STAY,i);const attributes={categoryType:'STAY',galleryUrls:images,stayDetail:{propertyType:choose(propertyTypes,i),roomSizeSqM:24+(i%7)*12,maxGuests:guests,bedrooms,beds:[{type:'Queen',quantity:Math.ceil(guests/2)}],bathrooms:1+(i%2)},amenities:stayAmenities.slice(0,5).concat(gallery(stayAmenities.slice(5),i).slice(0,3)),policies:{checkInTime:'14:00',checkOutTime:'11:00',allowPets:i%4===0,allowSmoking:false,partyAllowed:false}};
 return{title:`[Mẫu] ${type} gần ${p.title} · ${String(i+1).padStart(3,'0')}`,description:`${note}\n\n${type} minh họa tại khu vực ${p.province}, dùng để thử tìm kiếm nơi ở quanh ${p.title}. Không gian ${attributes.stayDetail.roomSizeSqM} m² được bố trí ${bedrooms} phòng ngủ, tối đa ${guests} khách, ${attributes.stayDetail.bathrooms} phòng tắm. Tiện nghi mô phỏng gồm ${attributes.amenities.join(', ')}. Phù hợp kiểm thử chuyến đi ${choose(['cặp đôi','gia đình','nhóm bạn','lưu trú dài ngày'],i)}; vị trí ghim trên bản đồ là vị trí mẫu quanh địa danh.\n\nNhận phòng từ 14:00, trả phòng trước 11:00. Không hút thuốc trong nhà, không tổ chức tiệc; ${attributes.policies.allowPets?'có hỗ trợ thú cưng theo cấu hình mẫu':'không nhận thú cưng trong cấu hình mẫu'}. Giá niêm yết tính cho một đêm, chưa đại diện giá thị trường. Khách thử nghiệm cần chọn ngày, số người và xem lịch tồn kho. Địa danh đối chiếu: ${p.googleMapsUrl}`,category:'STAY',subCategory:'NONE',basePrice:350000+(i%24)*100000,priceUnit:'PER_NIGHT',thumbnailUrl:images[0],attributes,capacity:1+(i%5)};
}
function experience(p,i){const images=[p.image.secureUrl,...gallery(LISTING_IMAGE_POOLS.EXP,i).slice(0,4)];const [type,activity]=kindText[p.kind];const duration=90+(i%4)*30;return{title:`[Mẫu] ${choose(['Khám phá','Tản bộ và chụp ảnh','Tìm hiểu văn hóa quanh','Hành trình nhóm nhỏ quanh'],i)} ${p.title} · ${i+1}`,description:`${note}\n\nTrải nghiệm nhóm nhỏ minh họa quanh ${p.title}, ${p.province}, thuộc chủ đề ${type}. Lịch trình ${duration} phút mô phỏng hoạt động ${activity}. Đây là chương trình giả lập, không xác nhận quyền tổ chức tour hoặc quyền vào khu bảo tồn. Điểm hẹn ở khu vực lân cận là tọa độ mẫu để kiểm tra bản đồ.\n\nChương trình gồm đón nhóm, giới thiệu tuyến, các điểm dừng phù hợp và tổng kết. Bao gồm người hướng dẫn mẫu, nước uống và hướng dẫn an toàn; chưa bao gồm vé vào cửa, phương tiện đến điểm hẹn hoặc bữa ăn riêng. Chuẩn bị giày dễ đi, nước cá nhân và trang phục phù hợp; kiểm tra thời tiết, yêu cầu sức khỏe và quy định của điểm tham quan trước khi sử dụng dịch vụ thật. Nhóm tối đa 8 người, có lựa chọn Tiếng Việt và Tiếng Anh theo cấu hình. Giá tính theo khách. Google Maps: ${p.googleMapsUrl}\n\n${credit(p)}`,category:'EXP',subCategory:'NONE',basePrice:180000+(i%15)*50000,priceUnit:'PER_PAX',thumbnailUrl:images[0],attributes:{categoryType:'EXP',galleryUrls:images,expDetail:{durationMinutes:duration,difficulty:'Dễ đến vừa; tùy tuyến mẫu',languages:['Tiếng Việt','Tiếng Anh'],groupSize:{min:1,max:8},meetingPoint:`Điểm hẹn mẫu quanh ${p.title}; không phải địa chỉ nhà cung cấp thật`,meetingPointLat:p.latitude,meetingPointLng:p.longitude},inclusions:['Người hướng dẫn mẫu','Nước uống','Giới thiệu tuyến và lưu ý an toàn'],exclusions:['Vé tham quan','Di chuyển tới điểm hẹn','Bữa ăn riêng'],itinerary:[{time:'00:00',activity:'Đón nhóm, xác nhận nhu cầu và giới thiệu tuyến mẫu'},{time:'00:15',activity:`Hoạt động ${activity} theo điều kiện cho phép`},{time:`${Math.floor((duration-15)/60).toString().padStart(2,'0')}:${((duration-15)%60).toString().padStart(2,'0')}`,activity:'Nghỉ ngắn, chụp ảnh và tổng kết'}]},capacity:8};}
function service(p,i){const sub=choose(Object.keys(svc),i),s=svc[sub],images=gallery(LISTING_IMAGE_POOLS.SVC[sub],i);return{title:`[Mẫu] ${s.name} tại ${p.province} · ${p.title} · ${i+1}`,description:`${note}\n\n${s.desc}\n\nKhu vực phục vụ mô phỏng quanh ${p.title}, ${p.province}, bán kính tối đa 10 km. Khung tiếp nhận mẫu 08:00–18:00, cần chọn suất còn chỗ trên lịch. Khách xác nhận số người, địa điểm thực hiện, không gian chuẩn bị và nhu cầu đặc biệt trước buổi sử dụng. Người cung cấp mang dụng cụ chuyên môn theo cấu hình; khách chuẩn bị điện, nước sạch và khu vực phù hợp. Không bao gồm phát sinh ngoài gói đã liệt kê. Điểm ghim và giá là dữ liệu kiểm thử, ảnh không chứng minh cơ sở hay nhân sự có thật. Google Maps của địa danh lân cận: ${p.googleMapsUrl}`,category:'SVC',subCategory:sub,basePrice:150000+(i%16)*75000,priceUnit:['CHEF','PREPARED_MEALS','CATERING'].includes(sub)?'PER_PAX':'PER_HOUR',thumbnailUrl:images[0],attributes:{categoryType:'SVC_'+sub,galleryUrls:images,serviceDetail:s.details(i),logistics:{serveAtClientLocation:!['SPA','TRAINING'].includes(sub),maxTravelRadiusKm:10,equipmentRequiredFromClient:'Nguồn điện và nước sạch theo nhu cầu gói',deliveryTimeWindow:'08:00–18:00, theo suất đã chọn',facilityRequired:'Không gian sạch, đủ diện tích cho nhóm và dụng cụ',cleanupProvided:true,equipmentProvided:'Dụng cụ chuyên môn được liệt kê trong gói',setupTimeHours:1}},capacity:8};}
const reviewBody={STAY:['Trong kịch bản nghỉ cùng gia đình, phần hiển thị phòng ngủ, giường và số khách giúp chọn loại phòng dễ hơn. Mô tả tiện nghi và giờ nhận phòng đầy đủ; cần xem lại vị trí trước khi đặt dịch vụ thật.','Tình huống lưu trú dài ngày mô phỏng cho thấy phần bếp, khu giặt và chính sách được trình bày rõ. Mình muốn có thêm thông tin đường vào và hướng dẫn gửi xe trong phiên bản kinh doanh.','Dữ liệu thử cho chuyến đi nhóm nhỏ: ảnh minh họa tải được, giá theo đêm và lịch phòng dễ theo dõi. Đây là nhận xét giả lập để kiểm tra giao diện đánh giá.'],EXP:['Trong kịch bản tham gia nhóm nhỏ, lịch trình có điểm hẹn, thời lượng và các khoản bao gồm nên dễ chuẩn bị. Phần vé vào cửa và di chuyển được tách rõ để kiểm tra trước chuyến đi.','Tình huống trải nghiệm mẫu có hướng dẫn chuẩn bị giày và kiểm tra thời tiết. Mình muốn tuyến thực tế được xác nhận bởi đơn vị tổ chức trước khi triển khai bán tour.','Nhận xét mô phỏng cho giao diện: chương trình chia thành các bước, giới hạn nhóm và ngôn ngữ hiển thị đầy đủ. Ảnh địa danh minh họa giúp nhận diện khu vực.'],SVC:['Kịch bản sử dụng gói mẫu có chi tiết phạm vi phục vụ, dụng cụ và thời gian chuẩn bị. Giá và khung giờ được hiển thị rõ; các phát sinh nên được xác nhận trước dịch vụ thật.','Trong tình huống kiểm thử, phần mô tả gói giúp hiểu công việc bao gồm và phần khách cần chuẩn bị. Mình muốn bổ sung lịch trao đổi nhu cầu trước khi triển khai cung cấp thực tế.','Đánh giá giả lập cho mẫu dữ liệu: ảnh minh họa tải bình thường, thông tin gói và lịch còn suất đủ để thử quy trình lựa chọn. Không phải xác nhận đã sử dụng dịch vụ.']};
async function main(){const places=JSON.parse(fs.readFileSync(process.env.SEED_DESTINATIONS_FILE||path.join(__dirname,'destinations.json'))).destinations;if(places.length!==100||places.some(p=>!p.image.secureUrl||!highlights[p.title]))throw Error('100 fully uploaded destinations are required');const users=await accounts(),owners=users.filter(x=>x.roles.includes('HOST')),enterprises=users.filter(x=>x.roles.includes('ENTERPRISE')),guests=users.filter(x=>x.roles.includes('USER')&&!x.roles.includes('HOST')&&!x.roles.includes('ENTERPRISE'));if(owners.length<7||enterprises.length<3||guests.length<3)throw Error('Not enough existing seed accounts');const plan={schemaVersion:1,batchId:batch,createdAt:new Date().toISOString(),inventoryStart:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),inventoryDays:91,landmarks:[],complexes:[],listings:[],reviews:[],inventory:[],provenance:[]};
 for(let i=0;i<places.length;i++){const p=places[i];plan.landmarks.push({id:id('landmark:'+p.pageId),name:p.title,description:landmarkDescription(p),province:p.province,latitude:p.latitude,longitude:p.longitude,radiusMeters:['NATURE','NATIONAL_PARK'].includes(p.kind)?7000:3500,thumbnailUrl:p.image.secureUrl,galleryUrls:[p.image.secureUrl],isFeatured:i%4===0,status:'ACTIVE'});plan.provenance.push({landmarkId:id('landmark:'+p.pageId),title:p.title,wikipediaUrl:p.wikipediaUrl,wikidataId:p.wikidataId,googleMapsUrl:p.googleMapsUrl,province:p.province,provinceBasis:p.provinceBasis,image:p.image});}
 for(let i=0;i<30;i++){const p=places[(i*3)%places.length],owner=choose(enterprises,i),loc=coordinates(p,i);plan.complexes.push({id:id('complex:'+i),hostId:owner.id,name:`[Mẫu] Khu lưu trú ${p.province} ${i+1}`,description:`${note}\n\nTổ hợp lưu trú mẫu quanh ${p.title}, dùng thử nhóm phòng, căn hộ và dịch vụ đi kèm. Có khu tiếp nhận, khu sinh hoạt chung, bếp và chỗ đỗ xe theo cấu hình giả lập. Danh sách phòng trực thuộc có cùng chủ sở hữu để kiểm thử phân quyền và quản lý tồn kho. Không phải cơ sở đang kinh doanh. Địa danh tham khảo: ${p.googleMapsUrl}`,province:p.province,...loc,thumbnailUrl:choose(IMAGE_POOLS.COMPLEX,i),galleryUrls:gallery(IMAGE_POOLS.COMPLEX,i),status:'ACTIVE'});}
 for(let i=0;i<500;i++){let n,p,x,complex=null;if(i<220){n=i;p=places[(i<60?(i%30)*3:i)%100];x=stay(p,n);complex=i<60?plan.complexes[i%30]:(plan.complexes.find(c=>c.province===p.province&&Math.abs(c.latitude-p.latitude)<0.025&&Math.abs(c.longitude-p.longitude)<0.025)||null);}else if(i<360){n=i-220;p=places[(n*3)%100];x=experience(p,n);}else{n=i-360;p=places[(n*7)%100];x=service(p,n);}const listing={id:id('listing:'+i),hostId:complex?.hostId||choose(owners,i).id,complexId:complex?.id||null,...(complex?{latitude:complex.latitude,longitude:complex.longitude}:coordinates(p,i)),province:p.province,status:'ACTIVE',...x};delete listing.capacity;const ratings=[3+(i%3),4+((i+1)%2),4+((i+2)%2)];listing.averageRating=Math.round(ratings.reduce((a,b)=>a+b)/3*10)/10;listing.totalReviews=3;plan.listings.push(listing);
  for(let j=0;j<3;j++)plan.reviews.push({id:id('review:'+i+':'+j),listingId:listing.id,userId:choose(guests,i+j).id,rating:ratings[j],comment:`[Đánh giá mẫu/giả lập ${i+1}.${j+1}] ${choose(reviewBody[listing.category],i+j)} Tài nguyên: ${listing.title}. Không phải đánh giá của khách hàng thật hay giao dịch đã hoàn tất.`,images:[]});
  plan.inventory.push({id:id('inventory:'+i),listingId:listing.id,category:listing.category==='SVC'?'SVC_'+listing.subCategory:listing.category,scheduleConfig:{defaultQuantity:x.capacity,timeSlots:listing.category==='STAY'?[]:listing.category==='EXP'?expSlots:slots},isActive:true});
 }
 fs.writeFileSync(process.env.SEED_PLAN_FILE||path.join(__dirname,'plan.json'),JSON.stringify(require('./presentation').presentPlan(plan),null,2)+'\n');console.log(JSON.stringify({landmarks:100,complexes:30,listings:500,reviews:1500,inventoryConfigs:500,inventoryCalendars:(220+280*3)*91,regions:new Set(places.map(p=>p.province)).size,categories:plan.listings.reduce((a,l)=>(a[l.category==='SVC'?l.subCategory:l.category]=(a[l.category==='SVC'?l.subCategory:l.category]||0)+1,a),{})}));}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
