// Presentation labels are separate from provenance. Proper names remain intact.
const disclaimer='DỮ LIỆU MẪU phục vụ phát triển và kiểm thử GoTravel. Tên cơ sở, vị trí dịch vụ, giá, tiện nghi, lịch còn chỗ và đánh giá dưới đây là giả lập; không phải quảng cáo hay xác nhận nhận đặt chỗ của doanh nghiệp có thật. Ảnh dịch vụ là ảnh minh họa.';
function cleanText(value){return value.replace(disclaimer+'\n\n','').replace(/\[Mẫu\]\s*/g,'').replace(/\[Đánh giá mẫu\/giả lập/g,'[Đánh giá giả lập').replace(/mẫu dữ liệu/g,'dữ liệu').replace(/\s+mẫu(?!\s+(?:vật|đơn|thiết kế))(?=[\s;,.]|$)/g,'').replace(/\s{2,}/g,' ').trim();}
function cleanAttributes(value){if(typeof value==='string')return cleanText(value);if(Array.isArray(value))return value.map(cleanAttributes);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,cleanAttributes(v)]));return value;}
function presentPlan(input){const plan=structuredClone(input);for(const l of plan.listings){l.title=cleanText(l.title);l.attributes=cleanAttributes(l.attributes);let d=l.description.replace(disclaimer+'\n\n','');if(l.category==='STAY'){d=d.replace(' minh họa tại khu vực ',' tại khu vực ').replace(/, dùng để thử tìm kiếm nơi ở quanh ([^.]+)\./,' gần $1.').replace('Tiện nghi mô phỏng gồm','Tiện nghi gồm').replace('Phù hợp kiểm thử chuyến đi','Phù hợp chuyến đi').replace('; vị trí ghim trên bản đồ là vị trí mẫu quanh địa danh.','.').replace('có hỗ trợ thú cưng theo cấu hình mẫu','có hỗ trợ thú cưng').replace('không nhận thú cưng trong cấu hình mẫu','không nhận thú cưng').replace(', chưa đại diện giá thị trường','').replace('Khách thử nghiệm cần chọn ngày, số người và xem lịch tồn kho.','Chọn ngày, số người và kiểm tra lịch còn phòng trước khi đặt.');}
if(l.category==='EXP'){d=d.replace('Trải nghiệm nhóm nhỏ minh họa','Trải nghiệm nhóm nhỏ').replace('phút mô phỏng hoạt động','phút gồm hoạt động').replace('Đây là chương trình giả lập, không xác nhận quyền tổ chức tour hoặc quyền vào khu bảo tồn. ','').replace('Điểm hẹn ở khu vực lân cận là tọa độ mẫu để kiểm tra bản đồ.','Xác nhận điểm hẹn và điều kiện tiếp cận với người tổ chức trước chuyến đi.').replace('trước khi sử dụng dịch vụ thật','trước khi tham gia');l.attributes.expDetail.difficulty='Dễ đến vừa; tùy tuyến';l.attributes.expDetail.meetingPoint=l.attributes.expDetail.meetingPoint.replace('; không phải địa chỉ nhà cung cấp thật','; xác nhận vị trí cụ thể trước chuyến đi');}
if(l.category==='SVC'){d=d.replace('Khu vực phục vụ mô phỏng','Khu vực phục vụ').replace('Điểm ghim và giá là dữ liệu kiểm thử, ảnh không chứng minh cơ sở hay nhân sự có thật. ','');}
l.description=d.replace(/\s+mẫu(?!\s+(?:vật|đơn|thiết kế))(?=[\s;,.]|$)/g,'');}
for(const c of plan.complexes){c.name=cleanText(c.name);const d=c.description.replace(disclaimer+'\n\n','');c.description=d.replace('Tổ hợp lưu trú mẫu','Tổ hợp lưu trú').replace(/, dùng thử nhóm phòng, căn hộ và dịch vụ đi kèm\./,', gồm các nhóm phòng, căn hộ và dịch vụ đi kèm.').replace('theo cấu hình giả lập','theo cấu hình từng loại phòng').replace('Danh sách phòng trực thuộc có cùng chủ sở hữu để kiểm thử phân quyền và quản lý tồn kho.','Danh sách phòng trực thuộc được quản lý chung; lịch còn phòng và giá được hiển thị riêng cho từng lựa chọn. Khách kiểm tra số người, tiện nghi, giờ nhận phòng và chính sách trước khi chọn phòng.').replace('Không phải cơ sở đang kinh doanh. ','');}
for(const r of plan.reviews)r.comment=cleanText(r.comment);
plan.recordOrigins={batchId:plan.batchId,listings:'synthetic',complexes:'synthetic',reviews:'synthetic',landmarks:'public-sourced',presentationRevision:1};return plan;}
module.exports={presentPlan,cleanText};
