const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {connect}=require('./db');const {validate,counts}=require('./apply-plan');
const gateway=process.env.SEED_GATEWAY_URL||'http://127.0.0.1:5555';
async function get(endpoint){const r=await fetch(gateway+endpoint,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('API '+endpoint+' HTTP '+r.status);return r.json();}
async function main(){const plan=JSON.parse(fs.readFileSync(path.join(__dirname,'plan.json')));validate(plan);const ids=plan.listings.map(x=>x.id);const c=await connect('CatalogandListing'),b=await connect('BookingandInventory');const report={batchId:plan.batchId,checkedAt:new Date().toISOString(),checks:[],api:[]};try{
 const actual=(await c.query('SELECT id,title,description,attributes,average_rating,total_reviews,status,title_normalized,ST_SRID(location) AS srid FROM listings WHERE id=ANY($1::uuid[])',[ids])).rows;assert.equal(actual.length,500);const map=new Map(actual.map(x=>[x.id,x]));for(const l of plan.listings){const row=map.get(l.id);assert.equal(row.status,'ACTIVE');assert.equal(row.title,l.title);assert.equal(row.description,l.description);assert.deepEqual(row.attributes,l.attributes);assert.equal(Number(row.average_rating),l.averageRating);assert.equal(row.total_reviews,3);assert.ok(row.title_normalized);assert.equal(row.srid,4326);}
 const reviews=(await c.query('SELECT listing_id,count(*)::int AS n,count(DISTINCT user_id)::int AS users,round(avg(rating)::numeric,1) AS average,bool_and(comment LIKE $2) AS marked FROM reviews WHERE listing_id=ANY($1::uuid[]) GROUP BY listing_id',[ids,'[Đánh giá giả lập%'])).rows;assert.equal(reviews.length,500);for(const r of reviews){assert.equal(r.n,3);assert.equal(r.users,3);assert.ok(r.marked);assert.equal(Number(r.average),map.get(r.listing_id).average_rating*1);}
 const inventory=(await b.query("SELECT listing_id,count(*)::int AS n,count(DISTINCT date)::int AS days,min(date)::text AS first,max(date)::text AS last,bool_and(status='AVAILABLE' AND available_quantity>0 AND version=0) AS available FROM inventory_calendars WHERE listing_id=ANY($1::uuid[]) GROUP BY listing_id",[ids])).rows;assert.equal(inventory.length,500);let calendars=0;for(const r of inventory){assert.equal(r.days,91);assert.equal(r.first,plan.inventoryStart);assert.equal(r.n,plan.listings.find(l=>l.id===r.listing_id).category==='STAY'?91:273);assert.ok(r.available);calendars+=r.n;}assert.equal(calendars,96460);
 assert.equal(Number((await b.query('SELECT count(*) AS n FROM inventory_configs WHERE listing_id=ANY($1::uuid[]) AND is_active=true',[ids])).rows[0].n),500);
 assert.equal(Number((await c.query('SELECT count(*) AS n FROM landmarks WHERE id=ANY($1::uuid[]) AND status=$2 AND name_normalized IS NOT NULL',[plan.landmarks.map(l=>l.id),'ACTIVE'])).rows[0].n),100);
 report.checks.push({name:'500 complete active listings, JSON attributes and spatial search fields',passed:true},{name:'1500 labeled reviews and rating aggregates',passed:true},{name:'500 inventory configs, 96460 calendars, 91 distinct days each',passed:true});
 const end=new Date(plan.inventoryStart+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+2);const dateEnd=end.toISOString().slice(0,10);const types=['STAY','EXP',...Object.keys(require('../vietnam-data').LISTING_IMAGE_POOLS.SVC)];
 for(const type of types){const l=plan.listings.find(x=>x.category===type||x.subCategory===type);const detail=await get('/api/v1/catalog/listings/'+l.id);assert.equal(detail.data.id,l.id);assert.equal(detail.data.attributes.categoryType,l.attributes.categoryType);const rr=await get('/api/v1/catalog/listings/'+l.id+'/reviews');assert.equal(rr.data.totalElements,3);assert.equal(rr.data.content.length,3);assert.ok(rr.data.content.every(r=>r.comment.startsWith('[Đánh giá giả lập')));const available=await get('/api/v1/public/inventory/listings/'+l.id+'/availability?startDate='+plan.inventoryStart+'&endDate='+dateEnd);assert.ok(available.data.length>0);const search=new URLSearchParams({q:'',category:l.category,checkIn:plan.inventoryStart,checkOut:dateEnd,limit:'100',sortBy:'RATING',...(l.category==='SVC'?{subCategory:l.subCategory}:{})});const found=await get('/api/v1/search/listings?'+search);assert.ok(found.data.some(x=>ids.includes(x.id)),'Seeded listings must be discoverable and available: '+type);report.api.push({type,listingId:l.id,detail:true,reviews:true,availabilityRows:available.data.length,searchItems:found.data.length});console.log('API verified: '+type);}
 const landmarks=await get('/api/v1/catalog/listings/landmarks');assert.ok(plan.landmarks.every(l=>landmarks.data.some(x=>x.id===l.id)));const sample=plan.landmarks.find(x=>x.name==='Thác Bản Giốc')||plan.landmarks[0];const suggestions=await get('/api/v1/search/locations/suggest?q='+encodeURIComponent(sample.name));assert.ok(JSON.stringify(suggestions).includes(sample.id),'Autocomplete must expose the new location');report.api.push({landmarks:true,autocomplete:sample.name});
 const imageRefs=[];const walk=v=>{if(typeof v==='string'&&/^https?:/.test(v))imageRefs.push(v);else if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')Object.values(v).forEach(walk);};for(const [table,field]of[['landmarks','gallery_urls'],['complexes','gallery_urls'],['listings','attributes'],['reviews','images']]){const imageRows=(await c.query('SELECT '+(table==='reviews'?'': 'thumbnail_url,')+field+' FROM '+table)).rows;imageRows.forEach(walk);}const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../cloudinary-images.json')));const known=new Set(Object.values(manifest.assets).filter(e=>e.state==='verified').map(e=>e.secureUrl));report.images={references:imageRefs.length,unique:new Set(imageRefs).size,nonCloudinary:imageRefs.filter(u=>!u.startsWith('https://res.cloudinary.com/'+manifest.cloudName+'/image/upload/')).length,unverified:imageRefs.filter(u=>!known.has(u)).length};assert.equal(report.images.nonCloudinary,0);assert.equal(report.images.unverified,0);report.totals={catalog:await counts(c,['landmarks','complexes','listings','reviews']),booking:await counts(b,['inventory_configs','inventory_calendars','inventory_locks'])};report.success=true;report.completedAt=new Date().toISOString();fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({success:true,totals:report.totals}));
 }finally{await c.end();await b.end();}}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
